# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [3]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [4]:
A = np.arange(1, 16).reshape(3,5)

In [5]:
print(A) # total matrix
print() # tom rad
print("Antal dimension:",A.ndim) # Dimension 
print("Size:",A.size) # Size
print("Shape:",A.shape) # Shape
print("Datatype:",A.dtype) # Datatyp

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Antal dimension: 2
Size: 15
Shape: (3, 5)
Datatype: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [6]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [7]:
print("Elementwise subtraction")
print(B-C) # Elementwise subtraction
print()
print("Elementwise multiplication")
print(B*C) # Elementwise multiplication
print()
print("Matrix multiplication")
print(B@C) # Matrix multiplication

Elementwise subtraction
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise multiplication
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix multiplication
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [8]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
exponentiate_B = np.exp(B) 
print("Exponentiate:")
print(exponentiate_B)
print()

print("Minsta siffran i hela matrisen:")
min_value = np.min(B)
print(min_value)
print()

print("Minmum i varje rad:")
min_value_row = np.min(B, axis=1)
print(min_value_row)
print()

min_value_column = np.min(B, axis=0)
print("Minimum i varje kolumn:")
print(min_value_column)
print()

print("Index värdet för minsta siffran i hela matrisen:")
index_min_value = np.argmin(B)
print(index_min_value)
print()

print("Index värdet för minsta siffrorna i varje rad:")
index_min_values_row = np.argmin(B, axis=1)
print(index_min_values_row)
print()

print("Summan för alla element:")
sum_all_elements = np.sum(B)
print(sum_all_elements)
print()

print("Mean: ")
mean_column = np.mean(B, axis=1)
print(mean_column)
print()

print("Median:")
median_column = np.median(B, axis =1)
print(median_column)
print()



Exponentiate:
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minsta siffran i hela matrisen:
1

Minmum i varje rad:
[1 4 7]

Minimum i varje kolumn:
[1 2 3]

Index värdet för minsta siffran i hela matrisen:
0

Index värdet för minsta siffrorna i varje rad:
[0 0 0]

Summan för alla element:
45

Mean: 
[2. 5. 8.]

Median:
[2. 5. 8.]



### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [10]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [11]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [12]:
# Första siffran i slicen representerar första lagret i matrisen, vilket i denna 2D-matris innebär raden. När du inte anger en ytterligare siffra i slicen, så printas hela raden ut.
# Hade man angivit ytterligare en siffra i slicen, så hade enbart en siffra på rad och column enligt angivna siffror/slice skrivits ut, tex: A[1,2] output: 8 

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [13]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [14]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [15]:
for f in np.nditer(A):
    print(f)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [16]:
a = np.arange(30)
b = a.reshape((2, 3,-1 ))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [17]:
# Variabeln a skapas, med Numpy 30 siffror, från 0-29.
# Variabeln b skapas, som en en omformning av a variabeln, har istället formen 2,3,-1: 2 står för antal matriser, 3 står för antal rader i varje matris och -1 står i detta fall för 5 siffror. 
# Dom tre axlarna består av antal matriser, antal rader i varje matris, samt antal siffror i varje rad. Om man inte vet sista lagret/antal siffror i varje rad, 
# får man fram det automatiskt av Numpy genom att ange -1.      

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [18]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [19]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [20]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)


[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [21]:
# Funktion som tar emot två matriser och en opperation, kontrollerar att matriserna är np.ndarray, och att operationen är plus eller multiplikation. Samt att matriserna har samma form. 
# Samt gör uträkningarna matris addition och multiplikation. 

def add_mult_matrices(m1, m2, operation):
    if not (m1, np.ndarray) or not isinstance(m2, np.ndarray):
        print("Båda argumenten måste vara av nypen numpy.ndarray")

    if operation not in['add', 'multiply']:
        print("Operationen måste vara plus eller minus") 

    if operation == 'add':
        if m1.shape != m2.shape:
            print("För addition måste matriserna ha samma storlek")
        return m1 + m2          

    elif operation == 'multiply':
        if m1.shape != m2.shape:
            print("För multiplikation måste matriserna ha samma storlek") 
        return m1 @ m2    
    
# Testar funktionen 
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])

addition_result = add_mult_matrices( m1 ,m2, 'add')
print("addition result:\n", addition_result)

print()

multiply_result = add_mult_matrices(m1 ,m2, 'multiply')
print("Multiply resultat:\n", multiply_result)

addition result:
 [[ 6  8]
 [10 12]]

Multiply resultat:
 [[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [22]:
x = np.array([4,3])

# a) 1x2 dimensioner. 
dimension = x.ndim 
print("a)",dimension)

# b) 
b = 5 * x
print("b)",b)

# c) 
c = 3*x
print("c)",c)

# d) 
d = (5*x)+(3*x)
print("d)",d)

# e)
e = 8*x
print("e)",e)

# f)
f = 4*x-x
print("f)",f)

# g) Blir en kolumnvektor istället för en radvektor, 2x1 dimensioner.
g = x.T
print("g)",g)

# h) ej definerat 

# i) Normen av vektorn x
i = np.linalg.norm(x)
print("i)",i)


a) 1
b) [20 15]
c) [12  9]
d) [32 24]
e) [32 24]
f) [12  9]
g) [4 3]
i) 5.0


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [23]:
# Uppgift 10.2.1
A = np.array([[2,1,-1],[1,-1,1]])
B = np.array([[4,-2,1],[2,-4,-2]])
C = np.array([[1,2],[2,1]])
D = np.array([[3,4],[4,3]])
E = np.array([1,2])
I = np.array([[1,0],[0,1]])

# a)
a = 2*A
print("a):\n",a)

# b) 
b = (B-2*A)
print("b):\n",b)

# c) Jämför formen mellan C och E matriserna. 
if C.shape != E.shape:
    print("c): Matriserna behöver ha samma form")

# d)
d = (2*D)-(3*C)
print("d):\n",d)

# e) 
e = D + 2*D
print("d):\n",e)    

# f) 
f = 2*C -2*D
print("f):\n",f)    

# g) transformerar om A matrisen med hjälp av A.T. jämför sedan formen med B. 
if A.T.shape != B.shape:
    print("g): Matriserna behöver ha samma form")

# h)  
if A.shape != C.shape:
    print("h): Matriserna behöver ha samma form") 

# i) 
i = C @ D
print("i):\n",i)  

# j) 
j = C @ B
print("j):\n",j)  

# k) 
k = C @ I
print("k):\n",k) 

# I) 
i = A @ B.T
print("i):\n",i) 


a):
 [[ 4  2 -2]
 [ 2 -2  2]]
b):
 [[ 0 -4  3]
 [ 0 -2 -4]]
c): Matriserna behöver ha samma form
d):
 [[3 2]
 [2 3]]
d):
 [[ 9 12]
 [12  9]]
f):
 [[-4 -4]
 [-4 -4]]
g): Matriserna behöver ha samma form
h): Matriserna behöver ha samma form
i):
 [[11 10]
 [10 11]]
j):
 [[  8 -10  -3]
 [ 10  -8   0]]
k):
 [[1 2]
 [2 1]]
i):
 [[5 2]
 [7 4]]


In [37]:
# Uppgift 10.2.2
A = np.array([[2,3,4],[5,4,1]])

# Transponerar om matrisen A. 
A_transposed = A.T

utfall = A @ A_transposed

print("A @ A^T:\n",utfall)

A @ A^T:
 [[29 26]
 [26 42]]


In [49]:
# Uppgift 10.2.3
A = np.array([[1,2],[2,4]])
B = np.array([[2,1],[1,3]])
C = np.array([[4,3],[0,2]])

AB = A @ B
print("AB:\n",AB)

AC = A @ C
print("AC:\n",AC)

if not np.array_equal(B, C):
     print("B != C, B är ej lika med C")


AB:
 [[ 4  7]
 [ 8 14]]
AC:
 [[ 4  7]
 [ 8 14]]
B != C, B är ej lika med C


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [24]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [25]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [26]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [27]:
# Med metoden np.may_share_memory() kan du kontrollera de är en view eller kopia, om true, delar de dataplats/view. Om False är de oberoende, v2 är då en kopia av v1.
view = np.may_share_memory(v1, v2)
print(view)

# När du använder slicing i Numpy skapas en view och inte en kopia. Det betyder att ändringar i v2 påverkar v1 och vice versa eftersom de pekar på samma data i minnet. 

True
